f = open('/app/app/models/user.py')
c = f.read()
f.close()
c = c.replace('"Office"', 'Office')
c = c.replace('"Role"', 'Role')
f = open('/app/app/models/user.py', 'w')
f.write(c)
f.close()
print('Done')
