f = open('/app/app/models/user.py')
c = f.read()
f.close()
c = c.replace('        back_populates="role",\n', '')
c = c.replace('        back_populates="users",\n', '')
f = open('/app/app/models/user.py', 'w')
f.write(c)
f.close()
print('Done')
